---
- name: Add share.bxota.com block to Caddyfile
  blockinfile:
    path: /opt/caddy/Caddyfile
    marker: "# {mark} olftransfer"
    block: |
      share.bxota.com {
          reverse_proxy olftransfer_app:8000
      }
  notify: Reload Caddy
